version: 0.2

phases:
  install:
    commands:
        - sudo add-apt-repository ppa:deadsnakes/ppa
        - sudo apt-get update
        - sudo apt-get install python3.6
        - sudo apt install python3-pip
        - echo y
        - sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1
        - python3 -m pip install Flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
